services:
  - type: web
    name: ride-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 7675978283:AAFjphYQTR4orJa42-UmxwTz2oDL5TTWx3U
